server:
  port: 8081

spring:
  application:
    name: coinstarter
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/my/h2/h2 # jdbc:h2:file:<filepath>
    username: sa
    password: